name: selivia drawings
analytics: {}
content_rating:
  adult: false
github: true
opengraph: {}
author: {}
color:
  lightness: 0.8129516883783395
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
  saturation: 0.8855618429103778
  brandStrength: 0.8502137753763734
  rhythmicContrast: 0.7329973403208417
